### ISSUE TITLE
How to handle file download if there is no href attribute in DOM

### ISSUE THREAD

**Issue by gihanmaduranga** [Ardesco/Ebselen#5]
Hi Mark,

Your project is really helpful.I am having some difficulties with file downloading if there is no `href `attribute located in DOM.In my case Dom element trigger a java script function and do the rest of things.so I would like to know that how can i handle that kind of scenario. appreciate any feedback.

[More details](http://stackoverflow.com/questions/37784108/how-can-i-get-the-file-url-from-web-element-if-it-calls-java-script-function-in/37784590#37784590)

Thanks.

**Comment by Ardesco** [comment]
I would suggest not using this any more.  This was written years ago and is full of bad practise.  You are better off looking at:

https://github.com/Ardesco/Selenium-Maven-Template

https://github.com/Ardesco/Powder-Monkey

http://ardesco.lazerycode.com/index.php/2012/07/how-to-download-files-with-selenium-and-why-you-shouldnt/

Or get a copy of my book:

https://www.amazon.co.uk/Mastering-Selenium-WebDriver-Mark-Collin/dp/1784394351/ref=sr_1_1?s=books&ie=UTF8&qid=1465822547&sr=1-1&keywords=mastering+selenium+webdriver

For you specific problem you are going to have to find out which javascript function is triggered and use a JavascriptExecutor to trigger it.  There's a chapter in the book about doing this sort of thing.

Hope all that helps.

**Comment by gihanmaduranga** [comment]
Thanks for quick feedback.
