### ISSUE TITLE
How do I re-use this code for Serenity BDD?

### ISSUE THREAD

**Issue by rakeshnambiar** [Ardesco/Ebselen#6]
How do I re-use this code for Serenity BDD?

**Comment by Ardesco** [comment]
you don't, this is massively obsolete.  If you want to see something up to date have a look at https://github.com/Ardesco/Selenium-Maven-Template.

Unfortunately Serenity BDD seems to be hooked into jUnit so you would need to swap out the TestNG implementation and switch over to jUnit in the above if you wanted to extend it to use Serenity BDD.
